#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#    Oct 14, 2019 01:53:44 PM +07  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    from pageemployee import empcontrol
    empcontrol = empcontrol.empcontrol(w)
    w.Listbox1.bind('<<ListboxSelect>>',empcontrol.onselect)
    w.Button1.configure(command=empcontrol.addemployee)
    w.Button2.configure(command=empcontrol.editemployee)
    w.Button3.configure(command=empcontrol.delemployee)

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def start():
    from pageemployee import employee
    employee.vp_start_gui()




